config/routes.rb
Rails.application.routes.draw do

  resources :tasks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
 def index
   @tasks = Task.all
 end

 def show
   @task = Task.find(params[:id])
 end

 def new
   @task = Task.new
 end

 def create
   Task.create(name: params[:task][:name])
   redirect_to tasks_path
 end

 def edit
   @task = Task.find(params[:id])
 end

 def update
   @task = Task.find(params[:id])
   @task.update(name: params[:task][:name], status:params[:task][:status])
   redirect_to tasks_path
 end

 def destroy
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTasksManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<p>Find me in app/views/tasks/edit.html.erb</p>


<%= form_for @task do |f| %>
 <%= f.label :name %>:
 <%= f.text_field :name %>

 <%= f.label :status %>:
 <%= f.text_field :status %>

 <%= f.submit "Edit" %>
<% end %>

app/views/tasks/index.html.erb
<h1>Tasks#index</h1>
<p>Find me in app/views/tasks/index.html.erb</p>

<ul>
 <% @tasks.each do |task| %>
 <li><%= link_to task.name, task_path(task) %></li>
 <% end %>
</ul>

app/views/tasks/new.html.erb
<h1>Tasks#new</h1>
<p>Find me in app/views/tasks/new.html.erb</p>

<%= form_for @task do |f| %>
 <%= f.label :name %>:
 <%= f.text_field :name %>

 <%= f.label :status %>:
 <%= f.text_field :status %>

 <%= f.submit "Create" %>
<% end %>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>

<h2><%= @task.name %></h2>
<p><%= @task.status %></p>